version: '3.7'

services:
#  kratos-migrate:
#    image: oryd/kratos:latest
#    environment:
#      - DSN=mysql://root:1234%qwerT@tcp(192.168.0.155:3307)/kratos?parseTime=True&max_conns=20&max_idle_conns=4
#    volumes:
#      - ./contrib/quickstart/kratos/email-password:/etc/config/kratos
#    command:
#      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
#    restart: on-failure
#    networks:
#      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:latest
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=cookie
    networks:
      - intranet
    restart: on-failure
    ports:
      - "4455:4455"

  kratos:
#    depends_on:
#      - kratos-migrate
    image: oryd/kratos:latest
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=mysql://root:1234%qwerT@tcp(192.168.0.155:3307)/kratos?parseTime=True&max_conns=20&max_idle_conns=4
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      - ./contrib/quickstart/kratos/email-password:/etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:
